spring:
  security:
    user:
      name: api
      password: api
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  batch:
    jdbc:
      initialize-schema: always
      platform: h2
    job:
      enabled: false
  sql:
    init:
      platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: false
    show-sql: true
  redis:
    replicated:
      nodes: redis://localhost:5379
  data:
    mongodb:
      uri: mongodb://root:example@localhost:5017
      database: datalake
    redis:
      database: 1

h2:
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password: 'pass'

salesdb:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mlqs-data-warehouse
    user: postgres-user
    password: postgres-pass

files:
  employees:
    path: "./employees.csv"
  images:
    path: "./images"

buckets:
  images:
    url: http://localhost:5500
    access: your_access_key
    secret: your_secret_key

server:
  port: 9090